[app]
# env 标记当前环境 分为 local test gray product
env="test"
# port 运行端口 暂定 joyread-go-api 使用 8801
port="8801"
# locales 当前项目包含的所有语言 初始化 mysql、redis 等配置时需要以这个数组为准 (也就是如果locales里包括了ko,后续的配置必须有 jwt_secret_ko,trace_log_path_ko,mysql_main_ko,mysql_split_ko,redis_main_ko,redis_statistic_ko等)
locales=[ "en", "es" ]
# 各语言的 trace log 目录
trace_log_path_en="/var/www/test/ENV_eng/app-novel-api/storage/logs"
trace_log_path_es="/var/www/test/ENV_spanish/app-novel-api/storage/logs"
trace_log_path_ru="/var/www/test/ENV_russian/app-novel-api/storage/logs"
trace_log_path_ko="/var/www/test/ENV_korean/app-novel-api/storage/logs"
trace_log_path_id="/var/www/test/ENV_indonesian/app-novel-api/storage/logs"

# mysql连接配置 包括主库 main 和分库 split
[mysql_main_en]
host="tokyo-test.cwm7e0x2qbl0.ap-northeast-1.rds.amazonaws.com"
port="3306"
username="test"
password="SVzudGlOj2h3CZL5"
database="test_joyread_en"

# 再同样设置其他语言的 mysql_main_xx

# redis连接配置 包括主库 main 和 statistic
[redis_main_en]
host="127.0.0.1"
port="6379"
password=""
db=0
pool_size=2
scheme="tcp"

# 再同样设置其他语言的 redis_main_xx

[aws_sqs]
queue="https://sqs.us-west-1.amazonaws.com/548071201873/test_joyread_member_hierarchy"
region="us-west-1"
timeout=0
access_key_id="AKIAX7G4W3RIRQ7JHNML"
secret_access_key="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"